name: CI
on: push
jobs:
  maybe_update_pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: regenerate pdf
      run: docker compose up
    - uses: stefanzweifel/git-auto-commit-action@v5.2.0
      with:
        commit_message: Autoupdate PDF
        commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
