name: CI
jobs:
  maybe_update_pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: regenerate pdf
      run: docker-compose up
    - uses: stefanzweifel/git-auto-commit-action@v4.2.0
      with:
        commit_message: Autoupdate PDF
